"""
SECONDARY PORT: Sandbox Executor Interface

Defines the contract for safely executing AI-generated Python code.

This is a critical security component of the Diagnostic Kernel.
The AI generates Python code that must be executed to determine next actions,
but we cannot trust arbitrary code execution without strict security measures.

Hexagonal Architecture: This is a SECONDARY PORT - an interface that the
application core uses to execute code safely. The core has zero knowledge of
the specific sandboxing technology (RestrictedPython).

Security Requirement:
Implementations must prevent AI-generated code from:
- Accessing the file system
- Making network requests
- Importing dangerous modules
- Executing system commands
- Accessing server memory or environment variables
"""

from abc import ABC, abstractmethod
from typing import Any


class ISandboxExecutor(ABC):
    """
    Secondary Port for safe execution of AI-generated Python code.

    Implementations must use sandboxing technology (like RestrictedPython)
    to execute code in a heavily restricted environment with minimal privileges.
    """

    @abstractmethod
    async def execute_code(self, code: str, params: dict[str, Any]) -> dict[str, Any]:
        """
        Execute AI-generated Python code in a secure sandbox.

        The code is expected to analyze the params and set a 'result' variable
        containing an action and payload:

        Example code the AI might generate:
            diagnosis_context = params["diagnosis_context"]
            if diagnosis_context["plant_vitals"] is None:
                result = {"action": "GET_PLANT_VITALS", "payload": {}}
            else:
                result = {"action": "ASK_USER", "payload": {"question": "How often do you water?"}}

        Args:
            code: Python code string generated by AI
            params: Dictionary passed to code (contains diagnosis_context)

        Returns:
            dict: The 'result' variable set by the code

        Raises:
            ValueError: If code has syntax errors, security violations, or no result
        """
        pass
